---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment2
spec:
  replicas: 10
  selector:
    matchLabels:
      app: trivial-go-web-app2
  template:
    metadata:
      labels:
        app: trivial-go-web-app2
    spec:
      containers:
      - name: webserver-simple2
        image: docker.io/kostiscodefresh/gitops-simple-app:v1.0
        ports:
        - containerPort: 8080
