apiVersion: v1
kind: Service
metadata:
  name: simple-service2
spec:
  type: NodePort
  selector:
    app: trivial-go-web-app2
  ports:
      - nodePort: 31001
        protocol: TCP
        port: 8081
